# 数据源1
spring:
  datasource:
    url: jdbc:sqlite::resource:db/xxqg_tiku.db
    driver-class-name: org.sqlite.JDBC

feishu:
  app-id: cli_a114bdbbf0fd100c
  app-secret: c8sT2troAtAuTbtQmnKrQdIe7QM8b5BC
  open-ids: 青山

forest:
  max-connections: 1000
  connect-timeout: 8000
  read-timeout: 8000
  log-response-content: false
server:
  port: 19011
  address: 0.0.0.0